fix: added migration check, disabled job cancelling and fix secrets usage

diff --git a/.github/workflows/production_deploy.yml b/.github/workflows/production_deploy.yml
--- a/.github/workflows/production_deploy.yml
+++ b/.github/workflows/production_deploy.yml
@@ -10,8 +10,34 @@ on:
       - README.md
   workflow_dispatch:
 
+concurrency:
+  group: deployment-production
+  cancel-in-progress: false
+
 jobs:
+  check-migrations:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "npm"
+
+      - run: npm ci
+
+      - name: Check Migrations
+        run: |
+          npx drizzle-kit generate
+          if [ -n "$(git status --porcelain drizzle/)" ]; then
+            echo "⚠️ Missing migration files! Please run npx drizzle-kit generate..."
+            exit 1
+          fi
+
   deploy:
+    needs: [check-migrations]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -37,4 +63,4 @@ jobs:
           VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
           VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
         run: |
-          npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
+          npx vercel deploy --prod --yes --token "$VERCEL_TOKEN"
